### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mbabatunde** [mbabatunde/mbabatunde.github.io#1]
~~- [x] Add PDF.js to website and upload PDF to Resume section~~
- [ ] Work on Projects section
- [x] Fix "CSS Jitter"
- [ ] Create a dark mode toggle feature
- [ ] Use PHP or JS for head, div header and footer, so I don't have to repeat all the tags on every page
- [ ] Run the entire site through W3C markup validation service to make sure everything is done correctly

**Comment by mbabatunde** [comment]
From some very little analysis, it appears that the rendering techniques found online for solving the CSS jitters/flickers work on Safari due to the use of manipulating webkit transformations.

However, said testing is not working on Chrome as nicely as it should. Possibly a V8 engine issue?

Further testing is needed, but these three lines work (I'll try to narrow it down to one after more testing):

`  -webkit-transform:translate3d(0,0,0);
    -webkit-backface-visibility: hidden;
    -webkit-transform-style: preserve-3d;`

**Comment by mbabatunde** [comment]
Did not need to use PDF.js to embed my resume. Google Drive allows you to embed a PDF with their iframe tag. Testing on mobile browsers needs to be done
